// <auto-generated />
using System;
using ChickenPlatesApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChickenPlatesApp.Migrations
{
    [DbContext(typeof(ChickenContext))]
    partial class ChickenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChickenPlatesApp.Models.ChickenPart", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("id");

                    b.ToTable("ChickenParts");
                });

            modelBuilder.Entity("ChickenPlatesApp.Models.ChickenPlate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("ChickenAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("DishId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<long>("PartId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sauce")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("PartId");

                    b.ToTable("ChickenPlates");
                });

            modelBuilder.Entity("ChickenPlatesApp.Models.Drink", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ChickenPlateId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChikenPlateId")
                        .HasColumnType("bigint");

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("id");

                    b.HasIndex("ChickenPlateId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("ChickenPlatesApp.Models.SideDish", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("varchar(250) CHARACTER SET utf8mb4")
                        .HasMaxLength(250);

                    b.HasKey("id");

                    b.ToTable("SideDishes");
                });

            modelBuilder.Entity("ChickenPlatesApp.Models.ChickenPlate", b =>
                {
                    b.HasOne("ChickenPlatesApp.Models.SideDish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChickenPlatesApp.Models.ChickenPart", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChickenPlatesApp.Models.Drink", b =>
                {
                    b.HasOne("ChickenPlatesApp.Models.ChickenPlate", "ChickenPlate")
                        .WithMany("Drinks")
                        .HasForeignKey("ChickenPlateId");
                });
#pragma warning restore 612, 618
        }
    }
}
